"""add due_date column to todo table

Revision ID: d9b25f58a7c3
Revises: 
Create Date: 2026-01-24 01:35:50.662473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9b25f58a7c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('conversation_thread_id_key', 'conversation', type_='unique')
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.drop_constraint('conversation_user_id_fkey', 'conversation', type_='foreignkey')
    op.drop_column('conversation', 'thread_id')
    op.add_column('message', sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('message', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('user', 'assistant', name='roletype'),
               existing_nullable=False)
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.add_column('todo', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_username_key', 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('todo', 'due_date')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.alter_column('message', 'role',
               existing_type=sa.Enum('user', 'assistant', name='roletype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('message', 'metadata_json')
    op.add_column('conversation', sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('conversation_user_id_fkey', 'conversation', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.create_unique_constraint('conversation_thread_id_key', 'conversation', ['thread_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('conversation', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
